### ISSUE TITLE
Kirkstone support

### ISSUE THREAD

**Issue by gevaerts** [jiazhang0/meta-secure-core#242]
Right now the master branch just supports honister. We're trying to update our system to kirkstone for LTS reasons. The bits of meta-secure-core we need (meta-tpm2, meta-efi-secure-boot, meta-encrypted-storage, meta-signing-key) seem to work fine. Can kirkstone be added to the LAYERSERIES_COMPAT variables?

**Comment by jiazhang0** [comment]
Done. https://github.com/jiazhang0/meta-secure-core/commits/master
