### ISSUE TITLE
util-linux package name extension causes build error

### ISSUE THREAD

**Issue by hdengler** [jiazhang0/meta-secure-core#30]
The package name extension to util-linux-switch_root.static causes a build error in my environment (based on poky pyro). As far as I know, the '\_' character is used as separator in yocto, therefore it should not be used in a package name.
In the attached patch, I replaed the '\_' with a '-', which fixed the build error. I'm not sure, if the '-' is the best choise, so maybe another replacement is also possible (allowed characters: [a-z0-9.+-]).

[0001-util-linux-Fix-package-name-extension.patch.txt](https://github.com/jiazhang0/meta-secure-core/files/1539213/0001-util-linux-Fix-package-name-extension.patch.txt)

**Comment by jiazhang0** [comment]
@hdengler Thanks for reporting this issue. I have pushed it https://github.com/jiazhang0/meta-secure-core/commit/0c4d9a8268561154b784bca595b65589f1f259d1

Please send a formal code review using Pull requests next time.
