### ISSUE TITLE
Failed to sign RPM packages: rpmsign: --signfiles: unknown option

### ISSUE THREAD

**Issue by WenzongFan** [jiazhang0/meta-secure-core#6]
Reproduce steps:
$ git clone git://git.yoctoproject.org/poky
$ git clone git://git.openembedded.org/meta-openembedded
$ git clone https://github.com/jiazhang0/meta-secure-core
$ cd poky; . ./oe-init-build-env ../build
$ echo 'DISTRO_FEATURES_append += "ima"' >> conf/local.conf

Add those layers to conf/bblayers.conf:
  /ala-lpggp51/wfan/yocto/meta-secure-core/meta-efi-secure-boot \
  /ala-lpggp51/wfan/yocto/meta-secure-core/meta-encrypted-storage \
  /ala-lpggp51/wfan/yocto/meta-secure-core/meta-integrity \
  /ala-lpggp51/wfan/yocto/meta-secure-core/meta-signing-key \
  /ala-lpggp51/wfan/yocto/meta-secure-core/meta-tpm \
  /ala-lpggp51/wfan/yocto/meta-secure-core/meta-tpm2 \
  /ala-lpggp51/wfan/yocto/meta-openembedded/meta-oe \
  /ala-lpggp51/wfan/yocto/meta-openembedded/meta-perl \

$ bitbake linux-yocto

ERROR: shadow-securetty-4.2.1-r3 do_package_write_rpm: Function failed: Failed to sign RPM packages: rpmsign: --signfiles: unknown option
ERROR: update-rc.d-0.7-r5 do_package_write_rpm: Function failed: Failed to sign RPM packages: rpmsign: --signfiles: unknown option

**Comment by jiazhang0** [comment]
@WenzongFan  Use SecureCore instead. Close this issue unless SecureCore has the same issue.

**Comment by WenzongFan** [comment]
There's no such issue with SecureCore, I missed below settings in local.conf:
DISTRO_FEATURES_NATIVE_append += "ima"

This enables the native rpmsign to support "--signfiles".

**Comment by yunguowei** [comment]
Not only native rpm/rpmsign needs this DISTRO_FEATURES, as we need to provide ima signature on target board at runtime, so DISTRO_FEATURES_append += "ima" is a better practice.

**Comment by WenzongFan** [comment]
I suggest to remove the 'INHERIT += "sign_rpm_ext"' from "meta-integrity/conf/layer.conf". It's a distro specific feature instead of default for the layer. Those settings should be combined for working:
+ DISTRO_FEATURES_append += "ima"
+ DISTRO_FEATURES_NATIVE_append += "ima"
+ INHERIT += "sign_rpm_ext"
